### ISSUE TITLE
Potential bug in GraphQLServlet?

### ISSUE THREAD

**Issue by jefrajames** [kumuluz/kumuluzee-graphql#2]
I think there is a bug in GraphQLServlet when more than 1 GraphApplicationClass has been discovered:

* A warning log message is produced on line 96,
* But the process flow is not interrupted and applicationClass is not initialized,
* this can result in a NullPointerException on line 101.

Correct me if I'm wrong.

**Comment by evader1337** [comment]
I have examined the code. I did write it in a strange way, but I think that the end result is the same whether there are more applications classes or none. The default application class (`GraphQLApplication.class`) just returns null values and empty arrays/maps for all the properties so it does not matter whether exception is thrown since it is gonna be handled in the catch block (but it is unnecessary to throw it). The only thing that happens is that the user with more applications classes will see two error messages: first the warning and then the second error from line 101. This should probably be changed in the next version, I agree.

**Comment by jefrajames** [comment]
You're right. The catch(Exception) enables the processing flow to continue. Even if it's not very purist ;-) BTW I'm part of the MicroProfile GraphQL initiative. I've played around with KumuluzEE GraphQL to get some inspiration and I've appreciated it. I'm preparing a Blog Post on KumuluzEE GraphQL that will be published on Jakarta EE Blog. Hope you will enjoy it!

**Comment by MBJuric** [comment]
Hi,
thanks for preparing a blog. That's great. If we can help with examples, please let me know. 
Have you sorted out the bug, or do you need some additional assistance from our side?
Thanks,
Matjaz

**Comment by jefrajames** [comment]
No I'm OK. Just playing around happily with KumuluzEE. I may have some questions to ask if you provide me an email. For instance, the use of @GraphQLApplicationClass annotation is not clear to me. I've defined my own GraphQLApplication class and it works.

**Comment by MBJuric** [comment]
With @GraphqlApplicationClass annotation, you can annotate a class instead of registering it manually as service provider. This simplifies the development. In KumuluzEE GraphQL, the project is scanned at compile time and classes annotated with @GraphqlApplicationClass are registered as service providers. This way the developers can use the @GraphqlApplicationClass annotation on their GraphQLApplication classes instead of registering them as service providers manually.

**Comment by MBJuric** [comment]
We have now modified the behavior when more than one GraphApplicationClass has been discovered. Also upped versions: https://github.com/kumuluz/kumuluzee-graphql/pull/3
After some testing we will make a new release.

**Comment by MBJuric** [comment]
We have released the new version, which fixes the issue. 
https://github.com/kumuluz/kumuluzee-graphql/releases/tag/v1.0.1
